from abc import ABC, abstractmethod
from app.models.schema_ir import DatabaseSchema, TableDefinition, ColumnDefinition, ColumnType, IndexDefinition


class SQLDialect(ABC):
    @abstractmethod
    def render_type(self, col: ColumnDefinition) -> str: ...
    @abstractmethod
    def uuid_default(self) -> str: ...
    @abstractmethod
    def ts_default(self) -> str: ...

    def render_column(self, col: ColumnDefinition) -> str:
        parts = [f'    "{col.name}"', self.render_type(col)]
        if col.name == "id":
            parts += ["NOT NULL", f"DEFAULT {self.uuid_default()}"]
        else:
            parts.append("NULL" if col.nullable else "NOT NULL")
            if col.default: parts.append(f"DEFAULT {col.default}")
            elif col.name in ("created_at","updated_at"): parts.append(f"DEFAULT {self.ts_default()}")
        if col.unique: parts.append("UNIQUE")
        if col.check_constraint: parts.append(f"CHECK ({col.check_constraint})")
        return " ".join(parts)

    def render_table(self, table: TableDefinition) -> str:
        lines = [f'CREATE TABLE IF NOT EXISTS "{table.name}" (']
        col_lines = [self.render_column(c) for c in table.columns]
        if table.primary_key:
            pk = ", ".join(f'"{c}"' for c in table.primary_key)
            col_lines.append(f"    CONSTRAINT pk_{table.name} PRIMARY KEY ({pk})")
        for fk in table.foreign_keys:
            name = fk.constraint_name or f"fk_{table.name}_{fk.column}"
            col_lines.append(
                f'    CONSTRAINT {name} FOREIGN KEY ("{fk.column}") '
                f'REFERENCES "{fk.references_table}" ("{fk.references_column}") '
                f'ON DELETE {fk.on_delete.value} ON UPDATE {fk.on_update.value}'
            )
        lines.append(",\n".join(col_lines))
        lines.append(");")
        if table.comment:
            lines.append(f"COMMENT ON TABLE \"{table.name}\" IS '{table.comment}';")
        return "\n".join(lines)

    def render_index(self, table_name: str, idx: IndexDefinition) -> str:
        u = "UNIQUE " if idx.unique else ""
        cols = ", ".join(f'"{c}"' for c in idx.columns)
        sql = f'CREATE {u}INDEX IF NOT EXISTS "{idx.name}" ON "{table_name}" USING {idx.index_type} ({cols})'
        if idx.condition: sql += f" WHERE {idx.condition}"
        return sql + ";"


class PostgreSQLDialect(SQLDialect):
    TYPES = {
        "INTEGER":"INTEGER","BIGINT":"BIGINT","SMALLINT":"SMALLINT",
        "DECIMAL":"DECIMAL","FLOAT":"DOUBLE PRECISION","BOOLEAN":"BOOLEAN",
        "VARCHAR":"VARCHAR","TEXT":"TEXT","CHAR":"CHAR","TIMESTAMP":"TIMESTAMP",
        "TIMESTAMPTZ":"TIMESTAMPTZ","DATE":"DATE","TIME":"TIME",
        "UUID":"UUID","JSONB":"JSONB","ARRAY":"TEXT[]",
    }
    def render_type(self, col):
        base = self.TYPES.get(col.type.value, "TEXT")
        if col.type == ColumnType.VARCHAR and col.length: return f"VARCHAR({col.length})"
        if col.type == ColumnType.DECIMAL and col.precision: return f"DECIMAL({col.precision},{col.scale or 2})"
        return base
    def uuid_default(self): return "gen_random_uuid()"
    def ts_default(self): return "NOW()"


class MySQLDialect(SQLDialect):
    TYPES = {"UUID":"CHAR(36)","BOOLEAN":"TINYINT(1)","TIMESTAMPTZ":"DATETIME","JSONB":"JSON","TEXT":"TEXT","VARCHAR":"VARCHAR","INTEGER":"INT","BIGINT":"BIGINT"}
    def render_type(self, col): return self.TYPES.get(col.type.value, "TEXT")
    def uuid_default(self): return "UUID()"
    def ts_default(self): return "CURRENT_TIMESTAMP"


class SQLGenerator:
    DIALECTS = {"postgresql": PostgreSQLDialect, "mysql": MySQLDialect}

    def generate(self, schema: DatabaseSchema) -> dict[str, str]:
        dialect = self.DIALECTS.get(schema.target_dialect, PostgreSQLDialect)()
        ordered = self._topo_sort(schema)
        table_sql = self._tables_sql(ordered, dialect, schema)
        index_sql = self._indexes_sql(schema, dialect)
        return {
            "001_create_tables.sql": f"BEGIN;\n\n{table_sql}\n\nCOMMIT;\n",
            "002_create_indexes.sql": f"BEGIN;\n\n{index_sql}\n\nCOMMIT;\n",
            "full_schema.sql": table_sql + "\n\n" + index_sql,
        }

    def _tables_sql(self, tables, dialect, schema):
        parts = [
            "-- ============================================",
            f"-- Schema: {schema.schema_name} | Dialect: {schema.target_dialect}",
            "-- Generated by NexSchema",
            "-- ============================================\n",
        ]
        for t in tables:
            if t.comment: parts.append(f"-- {t.comment}")
            parts.append(dialect.render_table(t))
            parts.append("")
        return "\n".join(parts)

    def _indexes_sql(self, schema, dialect):
        parts = ["-- Indexes\n"]
        for t in schema.tables:
            for idx in t.indexes:
                parts.append(dialect.render_index(t.name, idx))
        return "\n".join(parts)

    def _topo_sort(self, schema):
        graph = {t.name: {fk.references_table for fk in t.foreign_keys} for t in schema.tables}
        sorted_names, visited, temp = [], set(), set()
        def visit(n):
            if n in temp or n in visited: return
            temp.add(n)
            for dep in graph.get(n, set()): visit(dep)
            temp.discard(n); visited.add(n); sorted_names.append(n)
        for name in graph: visit(name)
        tm = {t.name: t for t in schema.tables}
        return [tm[n] for n in sorted_names if n in tm]
